Dockerfile.rhel

For some reason, `gpgme-devel` and `libassuan-devel` were not present during my attempt to build this image on brew, which made the build fail with the following error:
```
vendor/github.com/mtrmac/gpgme/data.go:4:20: fatal error: gpgme.h: No such file or directory
// #include <gpgme.h>
^
compilation terminated.
make: *** [build] Error 2
```
According to <https://github.com/openshift/openshift-controller-manager/blob/master/vendor/github.com/containers/image/README.md#building>, `libostree-devel` is also a requirement, but it built just fine on my tests without it.
I'm not sure if that is the best solution to the problem, was simply the minimum I needed to do in order to have a successful build; maybe we can have some input from @sosiouxme.

Install missing dependencies on OCP build

---

cmd/openshift-controller-manager/main.go

There are event recorders (template, apps, maybe others) which use the encoder from the legacy scheme. This is wrong: since openshift-apiserver is separate the types are not in that scheme anymore and should not be.
This PR is a quickfix against the CI fires. It should be reverted and all references to legacy scheme should be removed.

Quickfix: revive legacyscheme

---

pkg/build/buildutil/util.go
pkg/build/controller/build/build_controller.go
pkg/build/controller/build/build_controller_test.go
pkg/build/controller/strategy/util.go

@openshift/openshift-team-developer-experience fyi
/assign @bparees

Builds - Mount trusted CA for cluster proxies

---

pkg/build/controller/build/build_controller.go
pkg/build/controller/build/build_controller_test.go

When generating registries.conf, add the list of blocked registries from
config.Spec.RegistrySources.BlockedRegistries to the list of registries
in the [registries.block] section.
Signed-off-by: Nalin Dahyabhai <nalin@redhat.com>, Adam Kaplan <adam.kaplan@redhat.com>

Bug 1730722: Add blocked registries to registries.conf

---

pkg/build/buildutil/util.go
pkg/build/controller/build/build_controller.go
pkg/build/controller/build/build_controller_test.go
pkg/build/controller/strategy/util.go

…builds
/assign @bparees
per recent discussion on devex and warroom-proxy slack around https://bugzilla.redhat.com/show_bug.cgi?id=1748271
this consumes the config map created and labeled by ocm-o in PR https://github.com/openshift/cluster-openshift-controller-manager-operator/pull/118, vs. creating/labeling a configmap for each build, to access the global CA data.
If we are happy with this new approach, I'll label this PR for the bugzilla

Bug 1748271: Copy global CA data to builds

---

pkg/cmd/controller/security.go

I've added a leader lock in the NamespaceSCCAllocationController for upgrades 4.2->4.3
cluster-policy-controller container is split from openshift-controller-manager in 4.3 and will run in kube-controller-manager static pod
@deads2k

add leader lock for cluster-policy-controller upgrades

---

pkg/cmd/controller/image.go

```
apiserver_request_count{client="openshift-controller-manager/v0.0.0 (linux/amd64) kubernetes/$Format",code="0",component="apiserver",contentType="application/vnd.kubernetes.protobuf;stream=watch",endpoint="https",group="apps",instance="10.0.160.62:6443",job="apiserver",namespace="default",resource="statefulsets",scope="cluster",service="kubernetes",verb="WATCH",version="v1beta1"}
```
/cc @soltysh @adambkaplan

Use StatefulSets apps/v1 api, v1beta1 is going to be dropped

---

pkg/template/controller/readiness.go
pkg/template/controller/readiness_test.go

This is deprecated and we should be using apps/v1 instead.

Bug 1764498: Remove references to extensions/v1beta1.

---

pkg/cmd/controller/security.go

pick of e5eae1cec1da32a1bfed10eb35e1560ed20bd06d
requires this: https://github.com/openshift/cluster-kube-controller-manager-operator/pull/300
/cc @soltysh

Bug 1767047: add leader lock for cluster-policy-controller in scc_namespace_allocator controller

---

pkg/serviceaccounts/controllers/docker_registry_service.go
pkg/serviceaccounts/controllers/docker_registry_service_test.go

Exclude IPv6 addresses from the list of registry locations.
These are invalid locations to reference in an image pull spec.
Use IPv4 if IPv6 address is convertable.

Bug 1780376: Exclude IPv6 Registry Locations

---

pkg/serviceaccounts/controllers/create_dockercfg_secrets.go
pkg/serviceaccounts/controllers/deleted_dockercfg_secrets.go
pkg/serviceaccounts/controllers/deleted_token_secrets.go

Use default relist intervals when managing the service account pull secrets.
Current controllers never relist, potentially missing delete events.

Bug 1765294: Re-list pull secret controllers

---

pkg/route/ingress/ingress.go
pkg/route/ingress/ingress_test.go

When translating the port specified by an Ingress to the target port for a Route, use the port name rather than the number, or omit the target port if it has no name.
An Ingress resource specifies a Service and a port on that Service whereas a Route resource specifies a Service and a target port on the corresponding Endpoints resource.  The ports on the Endpoints resource and the ports on the Service resources have matching names but may have different numbers. Therefore, when mapping an Ingress and Service to a Route and a target port for the Endpoints resource, we cannot use port numbers; we must use names or omit the target port entirely.
It is safe to omit the target port if it does not have a name because a Service port must have a name if the Service has more than one port; …

Bug 1760776: ingress: targetPortForService: Use port name only

---

pkg/cmd/openshift-controller-manager/openshiftcontrolplane_default.go

Remove defaulting of the ServiceNetworkCIDR configuration.
This has been replaced by the cluster ingress configurations.

Remove ServiceNetworkCIDR Config

---

pkg/serviceaccounts/controllers/create_dockercfg_secrets.go
pkg/serviceaccounts/controllers/deleted_token_secrets.go
pkg/serviceaccounts/controllers/deleted_token_secrets_test.go
pkg/serviceaccounts/controllers/pull_secrets.go

Update the service account pull secret controller to add owner
references to generated pull secrets. This ensures pull secrets are
deleted when the associated token is deleted.

Bug 1765294: Use OwnerRefs to clean up SA pull secrets

---

pkg/build/controller/build/build_controller.go
pkg/build/controller/build/build_controller_test.go

aside from including init container, I'm including BuildPhaseError that build controller will set for containers that complete bug exit with non 0 rc
/assign @bparees 
@openshift/openshift-team-developer-experience fyi / ptal

Bug 1809862: report lastlogsnippet from init containers on failed/errored builds

---

pkg/serviceaccounts/controllers/create_dockercfg_secrets.go
pkg/serviceaccounts/controllers/docker_registry_service.go

Named queues will expose workload metrics to Prometheus.

Use Named Queues for Service Account Controller

---

pkg/cmd/controller/interfaces.go
pkg/cmd/controller/serviceaccount.go

Increase the k8s client QPS limit to 100, 200 burst for the service account pull secrets controller. This ensures that pull secrets for the registry are created as quickly as the tokens are generated.

Bug 1785023: Increase pull secrets controller QPS to 100

---

pkg/cmd/controller/ingress.go
pkg/route/ingress/ingress.go
pkg/route/ingress/ingress_test.go

https://bugzilla.redhat.com/show_bug.cgi?id=1801415

Bug 1801415: Migrate extensions/v1beta1 -> networking.k8s.io/v1beta1

---

pkg/apps/deployer/factory.go
pkg/apps/deploymentconfig/factory.go
pkg/build/controller/build/build_controller.go
pkg/build/controller/buildconfig/buildconfig_controller.go
pkg/image/controller/signature/signature_import_controller.go
pkg/project/controller/project_finalizer_controller.go
pkg/route/ingressip/service_ingressip_controller.go
pkg/unidling/controller/unidling_controller.go

* Add named queues for all ocm controllers
* This exposes the workqueue_* metrics to kube-state-metrics

Bug 1825324: Use named queues for all controllers

---

Dockerfile.rhel

Outcome of working session at https://coreos.slack.com/archives/CB95J6R4N/p1588170349277200 being able to use the golang 1.3 builder image used by brew/osbs 
Worked with @jupierce and @sosiouxme to line it up to install `gpgme-devel libassuan-devel` in that image
/hold
@adambkaplan @bparees FYI

Bug 1829863: update Dockerfile.rhel builder image to line up with art/brew/osbs

---

pkg/cmd/controller/image.go

We must check for v1 StatefulSets during update.

Bug 1831243: v1 StatefulSets do not trigger on image changes

---

pkg/cmd/controller/image.go

We must check for v1 StatefulSets during update.

Bug 1831245: StatefulSets v1 do not trigger on image changes

---

pkg/build/controller/strategy/custom.go
pkg/build/controller/strategy/docker.go
pkg/build/controller/strategy/sti.go
pkg/build/controller/strategy/util.go
pkg/build/controller/strategy/util_test.go

RunOnceDuration admission plugin no longer present in 4.x
/assign @adambkaplan

Bug 1829447: ensure build pod activeDeadlineSeconds always set

---

pkg/image/controller/scheduled_image_controller.go
pkg/image/controller/scheduled_image_controller_test.go

If an ImageStream tag refers to an image by SHA and we fail to import it
we need to allow the schedule process to take over an try again. With this
patch we now retry to import image stream tags based on SHA until it succeeds
at least once.
For further info on the reasoning behind this PR, please check https://coreos.slack.com/archives/CE2HALN2W/p1590050918461900

Bug 1829786: Allow scheduled retry of failed ImageStream import

---

Makefile
go.mod
go.sum
pkg/apps/deploymentconfig/factory.go
pkg/apps/metrics/prometheus/metrics.go
pkg/apps/metrics/prometheus/metrics_test.go

Add `strategy_total` metric to identify usage for different strategies. Also fixed a bug in counting `last_failed_rollout_time`.
Requires:
/cc @soltysh

Bug 1832294: Add strategy metrics

---

pkg/build/controller/build/build_controller.go
pkg/build/controller/build/build_controller_test.go

Builds which use postCommit hooks run in a container that references the image digest sha
directly. To buildah these images are "pulled" using the containers-storage transport, i.e
from local storage. Previously, we did not set any policy for containers-storage transport,
which meant we fell back to the default policy. The default policy is "reject all" in clusters
with an `AllowedRegistries` setting in `image.config.openshift.io/cluster`.
This fixes the generated signature policy.json file in builds so that images in
containers-storage can always be "pulled" and pushed.

Bug 1838372: Allow image push after postCommit script completes

---

pkg/image/controller/scheduler.go

Reverting-ish the scheduler logging removed as part of c0b49058a7.  This should help troubleshoot scheduled ImageStreams that get stuck, like a cluster running the 4.3 07837c7258 (#91) which had:
```console
$ oc describe is cli -n openshift
Name:             cli
Namespace:        openshift
Created:          24 hours ago
Labels:           <none>
Annotations:      <none>
Image Repository: default-route-openshift-image-registry.apps...
Image Lookup:     local=false
Unique Images:    0
Tags:             1
latest
updates automatically from registry quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:0a70026a8b193e61356054ab92ec825aac23c52ac5410c5e49c2412f92fe195b  ! error: Import failed (InternalError): Internal error occurred: quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:0a70026a8b1 …
```

pkg/image/controller/scheduler: Restore some logging

---

Dockerfile
Dockerfile.rhel

These packages are already present on the base image, no need to install
them during the image build.
This PR has been created so we can once again build release 4.4 after
changes on https://github.com/openshift/release/pull/9029

Bug 1819770: Removing yum commands from Dockerfile

---

pkg/cmd/controller/image.go

We must check for v1 StatefulSets during update.

Bug 1831888: StatefulSets v1 do not trigger on image changes

---

README.md
docs/metrics.md

Add basic `openshift-controller-manager` docs for users and contributors. This includes a README to
introduce the component, and a table of available metrics for monitoring.

Basic docs for OCM

---

pkg/route/ingress/ingress.go
pkg/route/ingress/ingress_test.go

Ingress objects are more common in the Kube ecosystem and have deeper
integration with other components. Right now they can not be used when a
terminationPolicy other than Edge is required. This PR changes that by
allowing to set an annotation on the Ingress.
cc @hongkailiu

Route ingress: Allow setting termination policy via annotation

---

pkg/build/controller/build/build_controller.go
pkg/build/controller/strategy/docker.go
pkg/build/controller/strategy/sti.go
pkg/build/controller/strategy/util.go

* Mount the cluster PKI trust bundle in a neutral location. openshift/builder is
responsible for copying this file to /etc/pki/ca-trust/source/anchors, then running
`update-ca-trust extract`. This will generate trust bundles for all types of processes
(email, TLS, JVMs, etc.).
* Use `Args` instead of `Command` when running builder image. This ensures the
entrypoint script for openshift/builder is always invoked.

Bug 1826183: Configure Build Pods to Merge CAs

---

pkg/route/ingress/ingress.go
pkg/route/ingress/ingress_test.go

First commit holds a script I used for testing, might be useful for others and is unlikely to cause harm.
I manually verified:
* Passthrough: Route gets created both when the Ingress has and has not a tls cert config 
* Reencrypt: Route gets created both when the Ingress has and has not a tls cert config and has the cert in the former case

Bug 1865784: Ingress to route controller: Make setting tls cert based on termination policy

---

pkg/cmd/controller/ingress.go
pkg/route/ingress/ingress.go
pkg/route/ingress/ingress_test.go

* `pkg/route/ingress/ingress.go` (`Controller`): Rename "client" to "routeClient".
(`NewController`, `sync`):
* `pkg/route/ingress/ingress_test.go` (`TestController_stabilizeAfterCreate`, `TestController_sync`): Use the new field name.
* `pkg/route/ingress/ingress_test.go`: Rename import of the fake clientset for the route API to "routev1fake".
(`TestController_stabilizeAfterCreate`, `TestController_sync`): Rename the fake clientset for the route API from "kc" to "routeClientset".  Rename "actions" to "routeActions".
* `pkg/route/ingress/ingress_test.go` (`TestController_sync`): Rename `wantCreates` to `wantRouteCreates`, `wantPatches` to `wantRoutePatches`, and `wantDeletes` to `wantRouteDeletes`.
* `pkg/cmd/controller/ingress.go` (`RunIngressToRouteController`): Pass ingress client to …

Bug 1820075: Reflect route status to ingress status

---

pkg/build/buildutil/util.go
pkg/build/buildutil/util_test.go

Label check should allow underscores, hyphens, and decimals in the name
instead of restricting to DNS RFC 1123 compatible values

Bug 1862532: Fix label value validation for Builds

---

Dockerfile
Dockerfile.rhel

ART builds for golang 1.12 do not include `gpgme-devel` and
`libassuan-devel`. Removing caused ART builds to fail.
Run `yum install` commands before setting the WORKDIR, because
the working directory does not exist in the container until
the COPY directive executes.

Bug 1849176: Revert "Remove unnecessary yum install"

---

pkg/build/buildutil/util.go
pkg/build/controller/build/build_controller.go
pkg/build/metrics/prometheus/metrics.go
pkg/build/metrics/prometheus/metrics_test.go

Add new `openshift_build_result_total` counter metric to the build controller.
This monotonically increments when any build reaches a terminal state on the
cluster. To keep the cardinality of this metric low, only `result` and
`strategy` labels are applied.`result` can have the values "failed" or
"success". Strategy is the lowercased build strategy type (`docker`, `source`,
`custom`, and `jenkinspipeline`).
Unlike the metrics reported by openshift-state-metrics, this counter will
continue to increase even if the build object is deleted by the build
controller's retention history feature.

Add Build Result Counter Metric

---

pkg/build/controller/buildconfig/buildconfig_controller.go
pkg/build/controller/buildconfig/buildconfig_controller_test.go
pkg/build/metrics/prometheus/metrics.go
pkg/build/metrics/prometheus/metrics_test.go

Detect if the lastTriggeredImageID was cleared in a BuildConfig.
If an update cleared the last triggered image, record a warning event.
A metric and associated alert were considered to better inform users
that deprecated behavior is being triggered. However, this was rejected
because the metric would require unbound time series cardinality.
The behavior that triggers builds off of `spec` will be removed in [BUILD-188](https://issues.redhat.com/browse/BUILD-188) [1].
[1] https://issues.redhat.com/browse/BUILD-188

BUILD-187: Detect if image trigger ID was cleared

---

pkg/route/ingress/ingress.go
pkg/route/ingress/ingress_test.go

BZ 1860136: Fix for Annotation was not propagated to the route when changes made to exisiting ingress object
BZ https://bugzilla.redhat.com/show_bug.cgi?id=1860136

Bug 1860136: Fix for Annotation was not propagated to the route when changes made to existing ingress object

---

pkg/build/controller/strategy/docker_test.go
pkg/build/controller/strategy/sti_test.go
pkg/build/controller/strategy/util.go

manual pick of https://github.com/openshift/openshift-controller-manager/pull/160 required
tests won't pass until https://github.com/openshift/builder/pull/207 merges
/assign @bparees 
@adambkaplan @jupierce FYI

remove use of BUILD_ISOLATION env var (no longer inspected in openshift/builder)

---

pkg/cmd/controller/unidling.go
pkg/unidling/controller/unidling_controller.go
pkg/unidling/controller/unidling_controller_test.go

Previously idle annotations were added to endpoints. In 4.6 the router
switched to watching endpointslices which don't have the idle
annotation. There was some upstream PRs/discussion to automatically
propagate existing annotations from endpoints to endpointslices:
https://github.com/kubernetes/kubernetes/pull/98116
As that was a non-starter we changed oc/idle to annotate the service
(and the endpoints for backwards compatibility). In the router we are
already watching service and and when we get endpoint changes we now
check for the idle annotation on the service. If it is present we
write the cluster-ip address into the haproxy.config as we previously
did prior to switching to endpointslices. We watch endpointslices for 
dual-stack and IPv6 support.
This change means that undiling needs …

Bug 1900989: unidling: switch away from endpoints to the service

---

pkg/cmd/controller/ingress.go
pkg/route/ingress/ingress.go
pkg/route/ingress/ingress_test.go

Update the ingress-to-route controller and unit tests to use the `networking.k8s.io/v1` API, implement IngressClass, and migrate routes created using older ingress API versions.
* `pkg/cmd/controller/ingress.go`: Update to import and use `networking/v1` packages.
(`RunIngressToRouteController`): Pass ingressclass client to `NewController`.
* `pkg/route/ingress/ingress.go`: Update to import and use `networking/v1` packages.
(`Controller`): Add `ingressclassLister` field.
(`NewController`): Add parameter for `ingressclasses` informer.  Use it to get `ingressclassLister`.
(`sync`): Check the ingress's `kubernetes.io/ingress.class` annotation and `spec.ingressClassName` field.  If an ingressclass is specified, look it up and check its `spec.controller` field value.  If the ingress specifies …

ingress: Migrate to networking.k8s.io/v1

---

pkg/build/controller/strategy/custom.go
pkg/build/controller/strategy/custom_test.go
pkg/build/controller/strategy/docker.go
pkg/build/controller/strategy/docker_test.go
pkg/build/controller/strategy/sti.go
pkg/build/controller/strategy/sti_test.go

Image on which `builder` is based, has been stripped from a lot of unnecessary files, including some locale files. Because of this, locale `en_US.utf8` does not exist in the builder image, which leads to `bsdtar` not working correctly with non-ansi files in the archive.
`C.utf8` does the job, though, and allows correct work with all the files.
Another possible solution would be installing `glibc-langpack-en` package in the `builder` image, but it would make the image bigger, and it doesn't seem like we really need `en_US` locale.

Bug 1935165: fixed LANG for the builder container

---

pkg/cmd/controller/image.go
pkg/image/controller/factory.go

When the controller imports an image from a slow registry, it waits for
a response from the registry and almost doesn't consume resources. As
today we have only 5 workers, 5 requests to import from a slow registry
will block the entire queue from beging processed.

Bug 1954715: Increase number of image-import controller workers

---

pkg/build/controller/build/build_controller.go
pkg/build/controller/build/build_controller_test.go
pkg/cmd/controller/build.go

In case `ConfigMap` or `Secret` in the `Build` `Spec` `Source` does not exist, build will now fail with corresponding reason and message.
There does not seem to be any reason for the build to wait for those resources, as their necessity is known before build creation.
Additionally, in case of the binary input, `Build` will fail if output does not exist.

Bug 1977414: fail Build if ConfigMap or Secret does not exist

---

pkg/image/controller/trigger/image_trigger_controller_test.go
pkg/image/trigger/buildconfigs/buildconfigs.go

Bug 2004203: BC ICT still must check spec last triggered image ID in case BC was last processed when cluster was pre 4.8

---

docs/metrics.md
pkg/unidling/controller/unidling_controller.go
pkg/unidling/metrics/doc.go
pkg/unidling/metrics/metrics.go

This metric will count the number of times this
event is seen and give an indication whether
idling is used.
Signed-off-by: Martin Kennelly <mkennell@redhat.com>

Add metric to count event with reason needPods

---

pkg/build/controller/build/defaults/defaults.go
pkg/build/controller/build/defaults/defaults_test.go
pkg/build/controller/common/testutil/pod.go

Use standard klog --v option to set log verbosity on Source and Docker
strategy builds, instead of our custom `--loglevel` option. The rebase
to k8s 1.23 prevents us from injecting the `--loglevel` option.

Bug 2034648: Use --v Option to Set Log Verbosity for Builds

---

cmd/openshift-controller-manager/main.go
pkg/cmd/openshift-controller-manager/cmd.go

One problem this fixes is during a node reboot when a SIGTERM
is given to the container it will stop in a timely fashion.
without this, the node has to wait for it's timeout (e.g., 30s)
before giving up and SIGKILL'ing it.
Signed-off-by: Jamo Luhrsen <jluhrsen@gmail.com>

Accept stop signal

---

pkg/build/controller/build/build_controller.go
pkg/build/controller/build/build_controller_test.go

Include the error string in the message that is set on the build
so that it is easily seen by the user, instead of them having to
dig through the OCM controller logs to find it.

Bug 2075584: Bubble actual error message up to the build

---

pkg/route/ingress/ingress.go
pkg/route/ingress/ingress_test.go

This PR is the continuation of #153. It adds the requests made on the original PR.
* The annotation now is a reference to a secret. The secret contains the CA to validate the backend certificate
* Added tests for this feature. 
* I've considered to change the annotation name to include "Secret" at the end. 
```yaml
kind: Ingress
apiVersion: networking.k8s.io/v1beta1
metadata:
annotations:
route.openshift.io/destination-ca-certificate-secret: <existing-secret-in-the-same-namespace>
route.openshift.io/termination: reencrypt
...
```
will generate: 
```yaml
kind: Route
metadata:
annotations:
route.openshift.io/termination: reencrypt
route.openshift.io/destination-ca-certificate-secret: <existing-secret-in-the-same-namespace>
spec:
...
tls:
termination: reencrypt
destinationCACertificate: | …
```

NE-860: ingress-to-route: add support for destinationCACertificate

---

pkg/build/controller/build/build_controller.go
pkg/build/controller/strategy/custom.go
pkg/build/controller/strategy/custom_test.go
pkg/build/controller/strategy/docker.go
pkg/build/controller/strategy/docker_test.go
pkg/build/controller/strategy/sti.go
pkg/build/controller/strategy/sti_test.go
pkg/build/controller/strategy/util.go
pkg/build/controller/strategy/util_test.go

In the build controller, we never actually called `setupContainersNodeStorage()`, so remove it, and stop setting the environment variable to force storage to use the overlay driver, which currently requires privileges, leaning on https://github.com/openshift/builder/pull/220 and https://github.com/openshift/builder/pull/291 to have the builder container figure that out for itself.
~Make the mode which we apply to secret and configuration map volumes in build pods something that the build controller can pass down to its helper functions, so that it can be adjusted based on the strategy.  Continue to default them to 0600.~
Set the seccomp profile for build pods to "unconfined", since we depend on `unshare()` and CRI-O is attempting to move away from allowing it to be used in its default …

BUILD-433: Run builds in user namespaces without seccomp if BUILD_PRIVILEGED=false

---

pkg/apps/deployer/deployer_controller.go
pkg/apps/deployer/deployer_controller_test.go

While debugging a deployer pod problem, I couldn't find the message I needed.  This leaves the current file location alone and it will continue to be used if present, but without it, the sysout will be used.
/assign @soltysh

update the deploy pod to provide failure in pod

---

pkg/build/controller/strategy/custom.go
pkg/build/controller/strategy/custom_test.go

When using a custom build strategy, mount config maps which were listed as sources, like we do for docker and sti builds.

OCPBUGS-10588: mount build.Spec.Source.ConfigMaps for custom builder images

---

pkg/build/controller/build/build_controller.go
pkg/build/controller/build/build_controller_test.go
pkg/cmd/controller/build.go

The epic is planned for 4.14: https://issues.redhat.com/browse/OCPNODE-1258
Update function signature from runtime-utils with idms, itms support. The [OCPNODE-521](https://issues.redhat.com//browse/OCPNODE-521) will land
new CRDs for image mirror configurations for 4.13.
The current components rely on ICSP should use new APIs.
ImageDigestMirrorSet implemented: openshift/machine-config-operator#3037
ImageDigestMirrorSet epic: https://issues.redhat.com/browse/OCPNODE-521

[OCPNODE-1258] update runtime-utils for idms migrations

---

pkg/cmd/controller/image.go
pkg/cmd/controller/interfaces.go
pkg/cmd/controller/template.go
pkg/template/controller/readiness.go

We don't run Build and DeploymentConfig controllers, if their capabilities are disabled. Whereas, ImageTrigger controller also relies on these resources in the form of informers and these informers are getting cached timeout error and causing the controller-manager being restarted multiple times.
This PR disables build and deploymentconfig informers, in cases where their caps are disabled to let imagetrigger can work properly.
This PR is continuation of this https://github.com/openshift/cluster-openshift-controller-manager-operator/pull/299

OCPBUGS-18498: Disable Build and DeploymentConfig Informers if their caps are disabled

---

go.mod
go.sum
pkg/template/controller/templateinstance_controller.go
vendor/github.com/openshift/library-go/pkg/template/templateprocessingclient/dynamic_process.go
vendor/modules.txt

Backport of https://github.com/openshift/openshift-controller-manager/pull/242 to release-4.11. It includes changes from https://github.com/openshift/library-go/pull/1598.
For context, this is required to fix templateinstance tests failures from https://github.com/openshift/openshift-apiserver/pull/400.
- https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_openshift-apiserver/400/pull-ci-openshift-openshift-apiserver-release-4.11-e2e-aws/1719006784351375360

OCPBUGS-23175: [release-4.11] fix template namespace processing

---

pkg/authorization/defaultrolebindings/defaultrolebindings.go
pkg/authorization/defaultrolebindings/defaultrolebindings_test.go
pkg/authorization/defaultrolebindings/project_policy.go
pkg/authorization/defaultrolebindings/project_policy_test.go
pkg/cmd/controller/authorization.go

This refactors the current [defaultsRoleBinding controller](https://github.com/openshift/openshift-controller-manager/blob/release-4.13/pkg/authorization/defaultrolebindings/defaultrolebindings.go#L41) into different controllers, responsible for managing respective roleBindings:
- defaultRoleBindingController -> system:image-pullers 
- builderRoleBindingController -> system:image-builders
- deployerRoleBindingController -> system:deployers
Dependent on:
- https://github.com/openshift/api/pull/1770
- https://github.com/openshift/cluster-openshift-controller-manager-operator/pull/335

BUILD-725: Adds build & deployer controller

---

pkg/build/buildutil/util.go
pkg/build/controller/build/build_controller_test.go

Build is looking for image pull secrets in the **ServiceAccount.Secrets** field, when it should be looking in the **ServiceAccount.ImagePullSecrets** field instead. 
In 4.16 we will stop putting image pull secrets in the **ServiceAccount.Secrets** field.

OCPBUGS-31213: Unable to look up the service account secrets for build

---

pkg/cmd/controller/pullsecrets.go
pkg/serviceaccounts/controllers/rollback/legacy_image_pull_secret_rollback_controller.go
pkg/serviceaccounts/controllers/rollback/legacy_image_pull_secret_rollback_controller_test.go
pkg/serviceaccounts/controllers/rollback/service_account-rollback-controller.go
pkg/serviceaccounts/controllers/rollback/service_account-rollback-controller_test.go

Cleanup service accounts and managed image pull secrets enough after an OCP downgrade from 4.16 such that the 4.15 controllers can take over successfully.
Related PRs:
- https://github.com/openshift/openshift-controller-manager/pull/288
- https://github.com/openshift/enhancements/pull/1574

OCPBUGS-32729: Rollback state of managed image pull secrets after downgrade.

---

pkg/cmd/controller/pullsecrets.go
pkg/serviceaccounts/controllers/rollback/legacy_image_pull_secret_rollback_controller.go
pkg/serviceaccounts/controllers/rollback/legacy_image_pull_secret_rollback_controller_test.go
pkg/serviceaccounts/controllers/rollback/service_account-rollback-controller.go
pkg/serviceaccounts/controllers/rollback/service_account-rollback-controller_test.go

* Revert: https://github.com/openshift/openshift-controller-manager/pull/301
* Fix: https://issues.redhat.com/browse/OCPBUGS-33088

OCPBUGS-32729: Rollback state of managed image pull secrets after downgrade

---

pkg/image/trigger/annotations/annotations.go
pkg/image/trigger/buildconfigs/buildconfigs.go

Handle getting a DeletedFinalStateUnknown instead of a runtime Object

OCPBUGS-33241: panic in image trigger controller

---

pkg/cmd/controller/config.go
pkg/cmd/controller/imageregistry.go
pkg/internalregistry/controllers/annotations.go
pkg/internalregistry/controllers/image_pull_secret_controller.go
pkg/internalregistry/controllers/keyid_observation_controller.go
pkg/internalregistry/controllers/legacy_image_pull_secret_controller.go
pkg/internalregistry/controllers/legacy_token_secret_controller.go
pkg/internalregistry/controllers/registry_urls_observation_controller.go
pkg/internalregistry/controllers/service_account_controller.go

- Revert https://github.com/openshift/openshift-controller-manager/pull/304
- Add fallback to alternate method of obtaining token signing key hash
On Hypershift, the image pull secrets were created, but not properly initialized due to the `image_pull_secret_controller` getting stuck waiting for the existence of the **bound-service-account-signing-key** secret in the **openshift-kube-apiserver** namespace.
Ideally, Hypershift would prefer to mount the service account signing key as as a volume on OCM pod. This would match what we already do this for the KCM pod. This PR provides an OCM-only fix to get us going until we make the changes to the way hypershift runs OCM.
Since what we need is the just the hash of the service account signing public key, if OCM does not find the …

OCPBUGS-33600: revert revert and fix for hypershift

---

pkg/build/buildutil/util_test.go
pkg/build/controller/build/defaults/defaults.go
pkg/build/controller/build/defaults/defaults_test.go

With https://github.com/openshift/api/pull/1659 additional env variables were whitelisted (proxy vars in lowercase). This commit adds testcases for all the whitelisted proxy env vars.

OCPBUGS-12699: Whitelists lower-case proxy envs to pod proxydefaults

---

pkg/cmd/controller/imageregistry.go
pkg/internalregistry/controllers/image_pull_secret_controller.go
pkg/internalregistry/controllers/service_account_controller.go

* The image-registry service account controller attempts to recover a clobbered annotation before deciding to creating a new one.
* The image-registry image pull secret controller cleans up orphaned managed image pulled secrets (deletes the secret and removes references from the service account). Note that references will remain in the service account if the secrets are deleted before applying this patch.

OCPBUGS-36833: 4.16 "Bad" reconciliation loops can cause unbounded dockercfg secret creation

---

pkg/cmd/controller/imageregistry.go
pkg/internalregistry/controllers/image_pull_secret_controller.go
pkg/internalregistry/controllers/service_account_controller.go

Reapplying #319 with fix for nil pointer dereference panic

Revert Revert OCPBUGS-36833: 4.16 "Bad" reconciliation loops can cause unbounded dockercfg secret creation

---

pkg/internalregistry/controllers/image_pull_secret_controller.go
pkg/internalregistry/controllers/legacy_token_secret_controller.go
pkg/internalregistry/controllers/service_account_controller.go

- Altered the apply API calls to prevent the re-creation of a service account deleted between the beginning of a control loop and the API call. 
- Hardened apply API calls for the manage image pull secrets to prevent accidental re-creation.
- improved handling of deletion events

OCPBUGS-35731: Race condition when deleting ServiceAccount

---

go.mod
vendor/modules.txt

This commit replaces all the references of [github.com/square/go-jose](https://github.com/square/go-jose) to [github.com/go-jose/go-jose@v2](https://github.com/go-jose/go-jose).

OCPBUGS-30704: replaces deprecated square/go-jose wtih go-jose/go-jose

---

go.mod
vendor/modules.txt

This commit replaces all the references of [github.com/square/go-jose](https://github.com/square/go-jose) to [github.com/go-jose/go-jose@v2](https://github.com/go-jose/go-jose).

OCPBUGS-32871: replaces deprecated square/go-jose wtih go-jose/go-jose

---

pkg/internalregistry/controllers/registry_urls_observation_controller.go

A duplicate in the list of registry URLs will cause the controller to think that all image pull secrets needs to be refreshed. This PR de-duplicates the list of registry URLs to prevent that.

OCPBUGS-42106: Continuous pull-secret updates / slow initialization on build01 (test platform infrastructure)

---

pkg/internalregistry/controllers/image_pull_secret_controller.go
pkg/internalregistry/controllers/image_pull_secret_controller_test.go

In some instances, the controller would re-queue an image pull secret in such a way that the check for an expiring token would only occur after the token had expired. This would result in a gap of time in which the pull secret contents would be invalid.

OCPBUGS-50507: Intermittent authentication issues when accessing OpenShift registry

---

pkg/build/controller/build/defaults/defaults.go

Problem:
Irrespective of default proxy settings these proxy variables are set on build containers.
If any defaults are set they reflect those setting ,if not set they are set to null on the build container. Having these null variables are causing problems to some customers as its breaking some required apps on container
HTTP_PROXY,http_proxy,HTTPS_PROXY,https_proxy,NO_PROXY,no_proxy
Fix:
Code changed only to add these proxy variables only if they are defined in defaults and if they are not null.

OCPBUGS-55826: Empty proxy variables are causing issues during the build

---

pkg/build/controller/build/defaults/defaults.go

Problem:
Irrespective of default proxy settings these proxy variables are set on build containers. If any defaults are set they reflect those setting ,if not set they are set to null on the build container. Having these null variables are causing problems to some customers as its breaking some required apps on container HTTP_PROXY,http_proxy,HTTPS_PROXY,https_proxy,NO_PROXY,no_proxy
Fix:
Code changed only to add these proxy variables only if they are defined in defaults and if they are not null.

OCPBUGS-56474: Empty proxy variables are causing issues during the build

---

pkg/build/controller/strategy/docker.go
pkg/build/controller/strategy/sti.go

This sets `ReadOnly: true` on the `node-pullsecrets`  volume to prevent pods from overwriting `/var/lib/kubelet/config.json`, which could cause image pull failures and expose sensitive credentials. This change is applied to both Docker and Source-to-Image build strategies.

[release-4.19] OCPBUGS-57193: Set node-pullsecrets volume to read-only to protect image pull credentials

---

pkg/build/controller/build/build_controller.go
pkg/build/controller/strategy/docker.go
pkg/build/controller/strategy/sti.go
pkg/build/controller/strategy/util.go
pkg/build/controller/strategy/util_test.go
pkg/cmd/controller/build.go

This PR removes all logic related to the BuildCSIVolumes feature gate from the openshift-controller-manager.
The BuildCSIVolumesEnabled flag along with its parsing logic, conditional checks, and related test cases has been fully removed. CSI volume support in Build pods is now considered stable and enabled by default, requiring no feature gate.
Originally, the BuildCSIVolumes feature gate was introduced to conditionally enable CSI (Container Storage Interface) volume mounts in Build pods. However, this functionality became generally available (GA) and permanently enabled starting with OpenShift 4.14, rendering the feature gate unnecessary.
As mounting CSI volumes into Build pods is now a standard, fully supported capability, all gate-specific logic is unnecessary and has been cleaned up. …

OCPBUGS-55650: Drop BuildCSIVolumes feature gate logic (Build CSI Volumes in OpenShift Builds is GA since 4.14) 

---

Dockerfile.rhel

- Add tests-ext-build target to container build process
- Gzip the openshift-controller-manager-tests-ext binary
- Copy gzipped OTE binary to /usr/bin/ in final image
- Fixes CI error: openshift-controller-manager-tests-ext.gz missing from container
This ensures the OTE binary is available for CI test execution on release-4.20.

OCPBUGS-61900:Fix Dockerfile.rhel: Add OTE binary build and packaging for release-4.20
