openshift/openshift-controller-manager

Dockerfile
=> make local dockerfile consistent

pkg/apps/OWNERS
we got dropped at the move
/cc @bparees
=> Add Apps owners back

pkg/apps/deploymentconfig/deploymentconfig_controller.go
/cc @soltysh 
one piece of https://github.com/openshift/origin/pull/22683
/hold
needs to be manually tested with new e2e in https://github.com/openshift/origin/pull/22683
=> Bug 1741133: Fix DC adoption

pkg/build/buildutil/util.go, pkg/build/controller/build/build_controller.go, pkg/build/controller/build/build_controller_test.go, pkg/build/controller/strategy/custom_test.go, pkg/build/controller/strategy/docker_test.go, pkg/build/controller/strategy/sti_test.go, pkg/build/controller/strategy/util.go, pkg/build/controller/strategy/util_test.go
Enable now that dependent PRs have merged
https://jira.coreos.com/browse/DEVEXP-401
/assign @bparees 
=> enable global injection of mounted trust CAs

pkg/image/controller/scheduled_image_controller.go, pkg/image/controller/scheduled_image_controller_test.go
/assign @dmage 
/assign @bparees
=> Bug 1755115: handle multiple tags when scheduling image imports

pkg/build/controller/build/build_controller.go
/assign @bparees - some additional questions came to my mind after coding the changes we talked about today
=> Bug 1753731: seeding of img registry hostname with config if needed

pkg/build/controller/build/build_controller.go
Fix race condition that may occur in build tests.
=> build: Report image registry host

pkg/build/controller/strategy/util.go, pkg/build/controller/strategy/util_test.go
=> Bug 1755140: add build ca bundle to init containers

pkg/build/controller/build/build_controller.go, pkg/build/controller/build/build_controller_test.go
@openshift/openshift-team-developer-experience fyi
=> Bug 1767218: Bug 1767219: don't enqueue non-existent buildconfigs for builds

pkg/route/OWNERS
Add the maintainers to a new OWNERS file.
=> Add ingress-to-route controller OWNERS

pkg/apps/metrics/prometheus/metrics.go, pkg/apps/metrics/prometheus/metrics_test.go, pkg/image/metrics/prometheus/metrics.go, pkg/image/metrics/prometheus/metrics_test.go, pkg/template/controller/metrics.go, pkg/template/controller/metrics_test.go, pkg/template/controller/readiness.go, pkg/template/controller/templateinstance_controller.go, pkg/template/controller/templateinstance_finalizer.go, pkg/version/version.go
* Fix DeploymentConfig, ImageStream, and TemplateInstance metrics
* Fix version info metric
=> Bug 1809699: Restore openshift-controller-manager metrics 

pkg/image/controller/trigger/image_trigger_controller.go
=> Bug 1813361: fix img reg ref on ICT if OCM knows img reg host before apiserver

go.mod, go.sum, vendor/github.com/mtrmac/gpgme/.appveyor.yml, vendor/github.com/mtrmac/gpgme/.travis.yml, vendor/github.com/mtrmac/gpgme/data.go, vendor/github.com/mtrmac/gpgme/go.mod, vendor/github.com/mtrmac/gpgme/go_gpgme.c, vendor/github.com/mtrmac/gpgme/go_gpgme.h, vendor/github.com/mtrmac/gpgme/gpgme.go, vendor/github.com/mtrmac/gpgme/unset_agent_info.go, vendor/github.com/mtrmac/gpgme/unset_agent_info_windows.go, vendor/modules.txt
Fixes [CVE-2020-8945](https://access.redhat.com/security/cve/CVE-2020-8945)
=> [release-4.3] Bug 1802889: bump(github.com/mtrmac/gpgme): v0.1.2

pkg/build/controller/build/build_controller.go, pkg/build/controller/build/build_controller_test.go
@bparees FYI in case you have cycles given your historical expertise
=> Bug 1815816: add 2 min retry on create build existing pod wrong owner (allow for GC)

pkg/cmd/openshift-controller-manager/controller_manager.go
=> Bug 1809719: use ReleaseOnCancel for leader election config

pkg/apps/deployer/factory.go, pkg/apps/deploymentconfig/factory.go, pkg/build/controller/build/build_controller.go, pkg/build/controller/buildconfig/buildconfig_controller.go, pkg/image/controller/signature/signature_import_controller.go, pkg/metrics/workqueue.go, pkg/project/controller/project_finalizer_controller.go, pkg/route/ingressip/service_ingressip_controller.go, pkg/unidling/controller/unidling_controller.go
attempting to implement guidance from https://bugzilla.redhat.com/show_bug.cgi?id=1832839#c10
=> Bug 1832839: more changes required for named workqueue metrics on pre 1.18 k8s base

Dockerfile, Dockerfile.rhel, pkg/build/controller/build/build_controller.go, pkg/build/controller/build/build_controller_test.go
Replacement for #122, which currently fails on CI because of an unnecessary `yum install` command.
Cherry pick of #114.
=> [release-4.3] Bug 1849176: Allow image push after postCommit script completes

pkg/unidling/controller/unidling_controller.go
Using chunking/pagination to `LIST` all events from the API Server.
=> Bug 1887745: Listing All Events with Chunking

pkg/build/controller/strategy/docker_test.go, pkg/build/controller/strategy/sti_test.go, pkg/build/controller/strategy/util.go
/assign @bparees 
@nalind @jupierce
=> remove use of BUILD_ISOLATION env var (no longer inspected in openshift/builder)

pkg/build/buildutil/util.go, pkg/build/controller/buildconfig/buildconfig_controller_test.go, pkg/image/controller/trigger/image_trigger_controller_test.go, pkg/image/trigger/buildconfigs/buildconfigs.go, pkg/image/trigger/buildconfigs/buildconfigs_test.go
/assign @adambkaplan
/assign @bparees
so here is the "POC" with https://github.com/openshift/api/pull/855 's changes manually copied in, to comply with @bparees 's ask in https://github.com/openshift/api/pull/855#issuecomment-789923610
once https://github.com/openshift/api/pull/855 merges I'll remove the manual copy, do the go mod bump, and remove the WIP
=> BUILD-186: build lastTriggeredID needs to be in status

pkg/build/OWNERS
Add reviewers/approvers from build team to pkg/build
=> Add OWNERS file to pkg/build

pkg/build/controller/build/build_controller.go, pkg/build/controller/build/build_controller_test.go
see https://github.com/openshift/builder/pull/266
/assign @adambkaplan
=> Bug 2011293: add Red Hat registries to the default registries.conf settings

pkg/image/controller/trigger/cache.go
If there is an error, the handler will currently log something like
```
unable to extract cache data from *v1.Deployment: unexpected end of JSON inpu
```
which is very difficult to map to an actual object. This PR changes that
error to also include the namespace and name of the object, if possible.
=> Image trigger handler: Include the object name on error

cmd/openshift-controller-manager/main.go, cmd/route-controller-manager/main.go, pkg/cmd/controller/route.go, pkg/cmd/controller/route/apiserver_authenticator.go, pkg/cmd/controller/route/apiserver_handlers.go, pkg/cmd/controller/route/config.go, pkg/cmd/controller/route/ingress.go, pkg/cmd/controller/route/metrics.go, pkg/cmd/controller/route/net.go, pkg/cmd/controller/route/standalone_apiserver.go, pkg/cmd/openshift-controller-manager/controller_manager.go, pkg/cmd/route-controller-manager/cmd.go, pkg/cmd/route-controller-manager/controller_manager.go, pkg/cmd/route-controller-manager/openshiftcontrolplane_default.go, pkg/cmd/routecontroller/route.go, pkg/routeversion/version.go
=> Bug 2117235: separate route controllers to a new command

.ci-operator.yaml, Dockerfile.rhel
Supersedes https://github.com/openshift/openshift-controller-manager/pull/229
=> Updating ose-openshift-controller-manager images to be consistent with ART

pkg/cmd/openshift-controller-manager/controller_manager.go
and run them only separately via [openshift-controller-manager route-controller-manager-start](https://github.com/openshift/openshift-controller-manager/blob/master/cmd/openshift-controller-manager/main.go#L69)
=> remove route controllers from OCM process (openshift-controller-manager start)

pkg/build/controller/build/build_controller.go, pkg/build/controller/strategy/docker.go, pkg/build/controller/strategy/sti.go, pkg/build/controller/strategy/util.go, pkg/build/controller/strategy/util_test.go, pkg/cmd/controller/build.go
This reverts commit adb4810cf2954c2c77c461a3e9fcfe51fbec67a7.
/hold
for a little longer, see if I can sort out hypershift req
=> BUILD-407: Revert "remove tech preview feature gate for build csi volumes"

LICENSE
Signed-off-by: Richard Fontana <rfontana@redhat.com>
=> Add explicit license

Dockerfile.rhel, pkg/cmd/controller/config.go, pkg/cmd/controller/imageregistry.go, pkg/internalregistry/controllers/annotations.go, pkg/internalregistry/controllers/image_pull_secret_controller.go, pkg/internalregistry/controllers/keyid_observation_controller.go, pkg/internalregistry/controllers/legacy_image_pull_secret_controller.go, pkg/internalregistry/controllers/legacy_token_secret_controller.go, pkg/internalregistry/controllers/registry_urls_observation_controller.go, pkg/internalregistry/controllers/service_account_controller.go
internal registry auth controllers
=> API-1644: Use bound service account tokens when generating pull secrets

pkg/internalregistry/controllers/legacy_image_pull_secret_controller.go, pkg/internalregistry/controllers/legacy_token_secret_controller.go, pkg/internalregistry/controllers/registry_urls_observation_controller.go
- **handle tombstones in filter handler**
=> OCPBUGS-33834: filter delete events

pkg/internalregistry/controllers/service_account_controller.go
The ServiceAccount.ImagePullSecrets field does not have a merge strategy defined. As such, when using (server-side) Apply to update the ImagePullSecrets field, we have to be careful to not clobber the contents added by other clients. This is in contrast to the ServiceAccounts.Secret field, where ownership is at the level of an individual entry in the list.
=> OCPBUGS-33815: openshift-controller-manager overwriting/undoing changes to ServiceAccount imagePullSecrets

OWNERS
Add team members to the OWNERS file for PR approvals and reviews
=> OCPBUGS-47527: Add team members to the OWNERS file

OWNERS
Added new team members to the OWNERS file
=> OCPBUGS-48656: Add new team members to the OWNERS file
